Models/PUBLISHART.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Artistesta.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.UI.WebControls;

    public partial class PUBLISHART
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PUBLISHART()
        {
            this.BIDDER = new HashSet<BIDDER>();
            this.COMMENTS = new HashSet<COMMENTS>();
            this.FAVORITES1 = new HashSet<FAVORITES>();
            this.INTERACTION = new HashSet<INTERACTION>();
        }
    
        public long ARTID { get; set; }
        public Nullable<int> USERID { get; set; }
        [Required(ErrorMessage = "Field Cannot Be Empty")]
        public string INSPIRATION { get; set; }
        public string ARTWORK { get; set; }
        [Required(ErrorMessage = "Field Cannot Be Empty")]
        public string TITLE { get; set; }
        public string TIME { get; set; } = DateTime.Now.ToString();
        [Required(ErrorMessage = "<br> Choose a category")]
        public string CATEGORY { get; set; }
        public Nullable<long> ENCOURAGES { get; set; }
        public Nullable<long> DISCOURAGES { get; set; }
        public Nullable<long> FAVORITES { get; set; }
        public Nullable<bool> ISPINNED { get; set; }
        public bool FORSALE { get; set; }
        public string MINIMUMBID { get; set; }
        public string AUCTIONID { get; set; }
        public string CURHIGHESTBID { get; set; }
        public string CURBIDDERID { get; set; }
        public string STATUS { get; set; } = "Pending";

        public HttpPostedFileBase File { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BIDDER> BIDDER { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COMMENTS> COMMENTS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FAVORITES> FAVORITES1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INTERACTION> INTERACTION { get; set; }
        public virtual USER USER { get; set; }



    }
    public enum cats
    {
        ABSTRACT,
        ANIMALS,
        ANIME,
        ARCHITECTURE,
        AUTOMOBILE,
        BLACKandWHITE,
        CITYSCAPE,
        GAMES,
        ILLUSTRATION,
        MISC,
        NATURE,
        OBJECTS,
        PORTRAIT,
        SKETCH,
        SUPERHERO,
        CALLIGRAPHY
    }
}

Controllers/PUBLISHARTsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Diagnostics;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Artistesta.Models;
using System.IO;
using System.Web.UI.WebControls;
using System.Security.Policy;

namespace Artistesta.Controllers
{
    public class PUBLISHARTsController : Controller
    {
        private ArtistestaEntities db = new ArtistestaEntities();

        // GET: PUBLISHARTs
        public ActionResult Index()
        {
            var pUBLISHART = db.PUBLISHART.Include(p => p.USER);
            return View(pUBLISHART.ToList());
        }

        // GET: PUBLISHARTs/Details/5
        public ActionResult Details(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PUBLISHART pUBLISHART = db.PUBLISHART.Find(id);
            if (pUBLISHART == null)
            {
                return HttpNotFound();
            }
            return View(pUBLISHART);
        }

        // GET: PUBLISHARTs/Create
        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.USERID = new SelectList(db.USER, "USERID", "USERNAME");
            return View();
        }

        // POST: PUBLISHARTs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(PUBLISHART pUBLISHART)
        {
            try {
                string path = Server.MapPath("~/ImageFiles");
                string fname = Path.GetFileName(pUBLISHART.File.FileName);
                string fpath = Path.Combine(path, fname);
                pUBLISHART.File.SaveAs(fpath);
                pUBLISHART.ARTWORK = fpath;
                var curid = Session["UserName"].ToString();
                var user = db.USER.Where(x => x.USERNAME.Equals(curid)).FirstOrDefault();
                var usid = user.USERID;
                pUBLISHART.USERID = usid;
                db.PUBLISHART.Add(pUBLISHART);
                db.SaveChanges();
                return RedirectToAction("Index");
            } 
            catch(DbEntityValidationException ex)
            {
                Debug.WriteLine(ex);
                return View();
            }
        }

        

        // GET: PUBLISHARTs/Edit/5
        public ActionResult Edit(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PUBLISHART pUBLISHART = db.PUBLISHART.Find(id);
            if (pUBLISHART == null)
            {
                return HttpNotFound();
            }
            ViewBag.USERID = new SelectList(db.USER, "USERID", "USERNAME", pUBLISHART.USERID);
            return View(pUBLISHART);
        }

        // POST: PUBLISHARTs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ARTID,USERID,INSPIRATION,ARTWORK,TITLE,TIME,CATEGORY,ENCOURAGES,DISCOURAGES,FAVORITES,ISPINNED,FORSALE,MINIMUMBID,AUCTIONID,CURHIGHESTBID,CURBIDDERID")] PUBLISHART pUBLISHART)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pUBLISHART).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.USERID = new SelectList(db.USER, "USERID", "USERNAME", pUBLISHART.USERID);
            return View(pUBLISHART);
        }

        // GET: PUBLISHARTs/Delete/5
        public ActionResult Delete(long? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PUBLISHART pUBLISHART = db.PUBLISHART.Find(id);
            if (pUBLISHART == null)
            {
                return HttpNotFound();
            }
            return View(pUBLISHART);
        }

        // POST: PUBLISHARTs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(long id)
        {
            PUBLISHART pUBLISHART = db.PUBLISHART.Find(id);
            db.PUBLISHART.Remove(pUBLISHART);
            db.SaveChanges();
            return RedirectToAction("admin", "Home");
        }

        public ActionResult Approve(long? id)
        {
            PUBLISHART art = db.PUBLISHART.Find(id);
            art.STATUS = "APPROVED";
            db.Entry(art).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("admin", "Home");
        }

        public ActionResult Disapprove(long? id)
        {
            PUBLISHART art = db.PUBLISHART.Find(id);
            art.STATUS = "Pending";
            db.Entry(art).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("admin", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/USERsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Artistesta.Models;

namespace Artistesta.Controllers
{
    public class USERsController : Controller
    {
        private ArtistestaEntities db = new ArtistestaEntities();

        // GET: USERs
        public ActionResult Index()
        {
            return View(db.USER.ToList());
        }

        // GET: USERs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            USER uSER = db.USER.Find(id);
            if (uSER == null)
            {
                return HttpNotFound();
            }
            return View(uSER);
        }

        // GET: USERs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: USERs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "USERID,USERNAME,FIRST_NAME,LAST_NAME,EMAIL,BIRTHDAY,PRONOUNS,COUNTRY,PASSWORD,DP,COVER,MOTTO,CARD_NO,CREATION_TIME")] USER uSER)
        {
            if (ModelState.IsValid)
            {
                db.USER.Add(uSER);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(uSER);
        }

        // GET: USERs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            USER uSER = db.USER.Find(id);
            if (uSER == null)
            {
                return HttpNotFound();
            }
            return View(uSER);
        }

        // POST: USERs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "USERID,USERNAME,FIRST_NAME,LAST_NAME,EMAIL,BIRTHDAY,PRONOUNS,COUNTRY,PASSWORD,DP,COVER,MOTTO,CARD_NO,CREATION_TIME")] USER uSER)
        {
            if (ModelState.IsValid)
            {
                db.Entry(uSER).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("admin", "Home");
            }
            return View(uSER);
        }

        // GET: USERs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            USER uSER = db.USER.Find(id);
            if (uSER == null)
            {
                return HttpNotFound();
            }
            return View(uSER);
        }

        // POST: USERs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            USER uSER = db.USER.Find(id);
            db.USER.Remove(uSER);
            db.SaveChanges();
            return RedirectToAction("admin", "Home");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Home/Index.cshtml
@using Artistesta.Models
@model  Artistesta.Models.USER

<!DOCTYPE HTML>
<html>
@{
    if (Session["UserName"].Equals(null))
    {
        Response.Redirect("Login", true);
    }
    var name = Model.FIRST_NAME + " " + Model.LAST_NAME;
    var dp = Model.DP;
    var cover = Model.COVER;

    ArtistestaEntities db = new ArtistestaEntities();
    var curid = Session["UserName"].ToString();
    var use = db.USER.Where(x => x.USERNAME.Equals(curid)).FirstOrDefault();
    var uid = use.USERID;
    var artsposted = db.PUBLISHART.Where(x => x.USERID==uid).OrderByDescending(x => x.ARTID).ToList();
}


<head>
    <link href="~/Content/style.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    <div class="padding pt-0 mt-0">

        <div style="float:right">
            @using (Html.BeginForm("Logout", "Home", FormMethod.Post))
            {
                <button onclick="document.forms[0].submit()" class="button" style="float:right; border-radius:30px; margin-top: 20px" value="">Log Out</button>
            }
        </div>
        <div class="card" style="border: none; opacity: 0.9; border-top-left-radius: 0; border-bottom-right-radius:25px; border-top-right-radius: 0; box-shadow: 0 0 20px 2px rgba(0,0,0,0.5); width: 70vw;">
            <img class="card-img-top" src="@cover" style="border-top-left-radius: 0; border-top-right-radius: 0;" alt="cover">

            <div class="card-body little-profile text-center">
                <div class="pro-img"><img src="@dp" alt="dp"></div>
                <h3 class="m-b-0">@name</h3>
                <p>@Model.MOTTO</p>
                <div class="row text-center m-t-20">
                    <div class="col-lg-4 col-md-4 m-t-20">
                        <h3 class="m-b-0 font-light">125</h3>
                        <small>Artworks</small>
                    </div>
                    <div class="col-lg-4 col-md-4 m-t-20">
                        <h3 class="m-b-0 font-light">195</h3>
                        <small>Followers</small>
                    </div>
                    <div class="col-lg-4 col-md-4 m-t-20">
                        <h3 class="m-b-0 font-light">55</h3>
                        <small>Following</small>
                    </div>
                </div>
            </div>

        </div>

    </div>

    @using (Html.BeginForm("Create", "PUBLISHARTs", FormMethod.Get, new { enctype = "multipart/form-data" }))
    {
        <a style="appearance:none; text-decoration:none;" href="~/PUBLISHARTs/Create">
            <div class="card" style="border-radius: 25px; opacity: 0.9; box-shadow: 0 0 20px 2px rgba(0,0,0,0.5); width: 70vw; margin: 20px;margin-top:30px; margin-left: -50px">

                <input style="width: 100%; padding: 20px; margin: 10px; border: none; appearance: none; cursor: pointer;" placeholder="Publish a new artwork" disabled />

            </div>
        </a>
    }


        @foreach (var art in artsposted)
        {
            art.ARTWORK = art.ARTWORK.Substring(System.Web.Hosting.HostingEnvironment.MapPath("~/").Length).Replace('\\', '/');

            <div id="status" style="width: 70vw; opacity: 0.9;align-content: start;margin: 20px; margin-left: -50px">
                <div style="width: 100%;">
                    <div style="border-bottom:solid thin;margin-bottom:0.5%;padding-bottom:1%;border-color:gray;margin-right:0;margin-left:0">
                        <a href="" style="color:  var(--base); text-decoration:none; font-size:xx-large">
                            <span style="margin-bottom:0.5%">
                                @art.TITLE
                            </span>
                        </a>
                        <div class="smallerText" id="time"
                             style="margin-top:1%; margin-bottom:10px;color: var(--base); float:right">
                            <div class="dropdown" style="margin-left:-37px;margin-top:0">
                                <i class="dropbtn fas fa-ellipsis-h" style="color:var(--base);font-size:large;"></i>
                                <div class="dropdown-content">
                                    <a onclick="" href="">Make available for auction</a>
                                </div>
                            </div>
                            <br>
                        </div>
                        <br>
                    </div>
                    <div style="border-bottom:solid thin;margin-bottom:0.5%;border-color:gray;margin-left:5px;margin-right:0">
                        <span style="text-align:left;margin-left:-1000px">
                            <a href="" style=" text-decoration:none;color: black">
                                <img src="~/Content/defaultDP.svg" style="border-radius:50%; width:3%;margin-bottom:0.5%">
                            </a>
                            <a href="" style="text-decoration:none;color: var(--base)">
                                <span class="" style="font-size:large"> @curid </span>
                            </a>
                        </span>
                        <span class="smallerText" id="time"
                              style="margin-top:1%; margin-bottom:10px;color: var(--base); float:right">
                            @art.TIME
                        </span>
                    </div>
                    <div style="margin-bottom:1px; margin-left:5px;border-bottom:solid thin;border-color:gray;">

                        <span class="" style=" font-size:larger; color:gray"> @art.INSPIRATION </span>
                    </div>
                    <div class="textsizeCorrect"
                         style="color:gray;margin-left: 2%;margin-right:0;border-bottom:solid thin;border-color:gray; padding-bottom:30px">
                        <div class="texts">
                            <p style='color:darkslategray;margin-top:-65px;margin-bottom:-80px;margin-left:-8.5%'>
                                <img src=@art.ARTWORK style="width:80%; border-radius:25px" />
                            </p>
                        </div>
                    </div>

                    <div id="reactSec">
                        <div class="react" style="padding-right:390px">

                            <a onclick='' href="" class="btn-with-hover" style="color: var(--col8); text-decoration:none;">
                                <i class="fa fa-thumbs-up" style="margin-left:-30%;font-size:3vh;color:var(--base)">
                                    <span style="font-size:15px;color:gray"> @art.ENCOURAGES </span>
                                </i>

                            </a>
                        </div>

                        <div class="react" style="border:none">
                            <a href="" class="btn-with-hover" style="color: var(--col8);">
                                <i class="fa fa-thumbs-down" style="font-size:3vh;color:var(--base)" aria-hidden="true">
                                    <span style="font-size:15px;color:gray"> @art.DISCOURAGES </span>
                                </i>
                            </a>
                        </div>
                    </div>


                </div>
            </div>
        }




        <!---->
        <!--<input type="text" id="title" name="title" value='' placeholder="Enter Title">-->








</body>
</html>
<script src="~/Scripts/bootstrap.bundle.min.js"></script>
<script src="~/Scripts/jquery-3.6.3.min.js"></script>
<script src="https://kit.fontawesome.com/4550e4897d.js" crossorigin="anonymous"></script>

Views/Home/Login.cshtml
@model Artistesta.Models.USER

@{
    ViewBag.Title = "Login";
}


<link href="~/Content/StyleSheet1.css" rel="stylesheet" />
<body style="background-image:url('../Content/background.jpg');background-size:cover "align="center">
    <div style="display:flex;margin-top:20px" align="center">


        <div style="float:left; margin-left:280px">
            <img src="~/Content/Artistesta.png" style="width:40vw;" />
        </div>


        <div style="float:right">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal form-box" align="center" style="margin-top:100px">
                    <h2 style="margin-bottom:80px">Sign In</h2>
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
              
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.USERNAME, new { htmlAttributes = new { @class = "form-control", PlaceHolder="Username",Style="Box-Shadow:none; width:100%" } })
                            @Html.ValidationMessageFor(model => model.USERNAME, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group"style="margin: 15px;">
                    
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.PASSWORD, new { htmlAttributes = new { @class = "form-control", Style = "Box-Shadow:none", PlaceHolder = "Password" } })
                            @Html.ValidationMessageFor(model => model.PASSWORD, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group"style="margin: 15px;">
                        <div class="col-md-offset-2 col-md-10">
                            <label style="color:red">@ViewBag.Text</label>
                        </div>
                    </div>

                    <div class="form-group" style="margin-top: 50px; margin-bottom: 10px;">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Login" class="btn button" />
                        </div>
                    </div>

                    <div>
                        @Html.ActionLink("Don't Have an account? Sign Up!", "Signup")
                    </div>

                </div>
            }
        </div>
    </div>
</body>



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Home/admin.cshtml
@using Artistesta.Models

@{
    ViewBag.Title = "admin";
    ArtistestaEntities db = new ArtistestaEntities();
    var alluser = db.USER.OrderByDescending(x => x.USERID).ToList();
    var allposts = db.PUBLISHART.OrderByDescending(x => x.ARTID).ToList();
}

<html>
<head>
    <link href="~/Content/style.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/StyleSheet.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;1,400;1,700&family=Source+Sans+Pro:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet" />
    <link href="~/Content/styler.css" rel="stylesheet" type="text/css" media="all" />

</head>

<body>

    <div class="padding pt-0 mt-0" style="opacity: 0.8">

        <nav class="header_wrapper navbar navbar-expand-sm fixed-top" style="background-color:black; margin-bottom:150px;">
            <div class="container-fluid justify-content-center" style="color:white">
                Admin Panel
            </div>
        </nav>

        <div id="tabs-section" class="tabs" style="width:90vw; height:96vh;margin-top:46px">
            <ul class="tab-head" style="width: 10vw; box-shadow: 0 0 1px 1px rgba(0,0,0,0.5); overflow-y:scroll ">
                <li>
                    <a href="#tab-1" class="tab-link active"> <span class="tab-label">Manage Users</span></a>
                </li>
                <li>
                    <a href="#tab-2" class="tab-link">  <span class="tab-label">Manage Posts</span></a>
                </li>
                <li>
                    <a href="#tab-3" class="tab-link">  <span class="tab-label">Arrange Auctions</span></a>
                </li>
            </ul>

            <section id="tab-1" class="tab-body entry-content active active-content" ; style="overflow-x:scroll; overflow-y:scroll">

                <table class="table">
                    <tr>
                        <th>
                            USERNAME
                        </th>
                        <th>
                            FIRST_NAME
                        </th>
                        <th>
                            LAST_NAME
                        </th>
                        <th>
                            EMAIL
                        </th>
                        <th>
                            BIRTHDAY
                        </th>
                        <th>
                            COUNTRY
                        </th>
                        <th>
                            PASSWORD
                        </th>
                        <th>
                            DP
                        </th>
                        <th>
                            COVER
                        </th>
                        <th>
                            CARD_NO
                        </th>
                        <th>
                            CREATION_TIME
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in alluser)
                    {
                        <tr>
                            <td>
                                @item.USERNAME
                            </td>
                            <td>
                                @item.FIRST_NAME
                            </td>
                            <td>
                                @item.LAST_NAME
                            </td>
                            <td>
                                @item.EMAIL
                            </td>
                            <td>
                                @item.BIRTHDAY
                            </td>
                            <td>
                                @item.COUNTRY
                            </td>
                            <td>
                                @item.PASSWORD
                            </td>
                            <td>
                                <img src=@item.DP style="width:100px" />
                            </td>
                            <td>
                                <img src=@item.COVER style="width:100px" />
                            </td>
                            <td>
                                @item.CARD_NO
                            </td>
                            <td>
                                @item.CREATION_TIME
                            </td>
                            <td>
                                @Html.ActionLink("Edit", "Edit", "USERs", new { id = item.USERID }, null) |
                                @Html.ActionLink("Delete", "Delete", "USERs", new { id = item.USERID }, null)
                            </td>
                        </tr>
                    }

                </table>


            </section>

            <section id="tab-2" class="tab-body entry-content" style="overflow-x:scroll; overflow-y:scroll">
                <table class="table">
                    <tr>
                        <th>
                            ARTWORK
                        </th>
                        <th>
                            TITLE
                        </th>
                        <th>
                            CATEGORY
                        </th>
                        <th>
                            Status
                        </th>
                        <th>
                            FORSALE?
                        </th>
                        <th>
                            MINIMUM BID
                        </th>
                        <th>
                            CURRENT HIGHEST BIDDER ID
                        </th>
                        <th></th>
                    </tr>

                    @foreach (var item in allposts)
                    {
                        item.ARTWORK = Url.Content("~/" + item.ARTWORK.Substring(50));
                        <tr>
                            <td>
                                <img src=@item.ARTWORK style="width:250px" />
                            </td>
                            <td>
                                @item.TITLE
                            </td>
                            <td>
                                @item.CATEGORY
                            </td>
                            <td>
                                @item.STATUS
                            </td>
                            <td>
                                @item.FORSALE
                            </td>
                            <td>
                                @item.MINIMUMBID
                            </td>
                            <td>
                                @item.CURHIGHESTBID
                            </td>
                            <td>
                                @item.CURBIDDERID
                            </td>
                            <td>
                                @if (item.STATUS == "Pending")
                                {
                                    @Html.ActionLink("Approve |", "Approve", "PUBLISHARTs", new { id = item.ARTID }, null)
                                    @Html.ActionLink("Delete", "Delete", "PUBLISHARTs", new { id = item.ARTID }, null)
                                }

                                else
                                {
                                    @Html.ActionLink("Disaprove |", "Disapprove", "PUBLISHARTs", new { id = item.ARTID }, null)
                                    @Html.ActionLink("Delete", "Delete", "PUBLISHARTs", new { id = item.ARTID }, null)
                                }

                            </td>
                        </tr>
                    }

                </table>
            </section>

            <section id="tab-3" class="tab-body entry-content">
            </section>
        </div>

    </div>

</body>
</html>
<script src="~/Scripts/bootstrap.bundle.min.js"></script>
<script src="~/Scripts/jquery-3.6.3.min.js"></script>
<script src="https://kit.fontawesome.com/4550e4897d.js" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="~/Scripts/TABBED.js"></script>